export const ActionType = {
  CATEGORIES_LOADING: 'CATEGORIES_LOADING',
  CATEGORIES_LIST: 'CATEGORIES_LIST',

  PRODUCTS_LOADING: 'PRODUCTS_LOADING',
  PRODUCT_LIST: 'PRODUCT_LIST',

  CART_LOADING: 'CART_LOADING',
  CART_LIST: 'CART_LIST',
};
